name: Golangci-Lint CI Workflow
on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - master
permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        go: [1.19]
        os: [ubuntu-latest]
    name: golangci-lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m --verbose